-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- Split config — each concern in modules/. Edit there.
-- Load order matters: vars first (shared), then config, then binds/rules, then autostart last.

require("modules.vars")
require("modules.monitors")
require("modules.env")
require("modules.look")
require("modules.animations")
require("modules.layouts")
require("modules.misc")
require("modules.input")
require("modules.windowrules")
require("modules.keybindings")
require("modules.autostart")

-- User-specific monitor overrides generated by nwg-displays (eDP-1).
-- Loaded AFTER modules.monitors so the specific rule wins over the generic default.
require("monitors")
