
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

require("modules.input")
require("modules.vars")
require("modules.autostart")
require("modules.monitors")
require("modules.keybindings")
require("modules.env")
require("modules.permission")
require("modules.window")
require("modules.misc")
require("modules.animation")

